version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    depends_on:
      - postgres
    env_file:
      - .env.development # Change this to the appropriate .env file for other environments
    command: node dist/main.js
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    image: postgres:16.3-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - user-management-postgres:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user-management-postgres:
